from werkzeug.exceptions import abort

def funcion_salir():
  return abort(404)